/*
 * Copyright 2022 Free Software Foundation, Inc.
 *
 * This file is part of GNU Radio
 *
 * SPDX-License-Identifier: GPL-3.0-or-later
 *
 */

/***********************************************************************************/
/* This file is automatically generated using bindtool and can be manually edited  */
/* The following lines can be configured to regenerate this file during cmake      */
/* If manual edits are made, the following tags should be modified accordingly.    */
/* BINDTOOL_GEN_AUTOMATIC(0)                                                       */
/* BINDTOOL_USE_PYGCCXML(0)                                                        */
/* BINDTOOL_HEADER_FILE(pulseaudio_source.h)                                        */
/* BINDTOOL_HEADER_FILE_HASH(13fafb5d4de921e11e01647aad82ab76)                     */
/***********************************************************************************/

#include <pybind11/complex.h>
#include <pybind11/pybind11.h>
#include <pybind11/stl.h>

namespace py = pybind11;

#include <hnch/pulseaudio_source.h>
// pydoc.h is automatically generated in the build directory
#include <pulseaudio_source_pydoc.h>

void bind_pulseaudio_source(py::module& m)
{

    using pulseaudio_source    = ::gr::hnch::pulseaudio_source;


    py::class_<pulseaudio_source, gr::sync_block, gr::block, gr::basic_block,
        std::shared_ptr<pulseaudio_source>>(m, "pulseaudio_source", D(pulseaudio_source))

        .def(py::init(&pulseaudio_source::make),
           py::arg("samplingrate"),
           py::arg("sourcename"),
           py::arg("outchans"),
           py::arg("latency_ms"),
           D(pulseaudio_source,make)
        )
        



        ;




}








