/*
 * Copyright 2023 Free Software Foundation, Inc.
 *
 * This file is part of GNU Radio
 *
 * SPDX-License-Identifier: GPL-3.0-or-later
 *
 */

/***********************************************************************************/
/* This file is automatically generated using bindtool and can be manually edited  */
/* The following lines can be configured to regenerate this file during cmake      */
/* If manual edits are made, the following tags should be modified accordingly.    */
/* BINDTOOL_GEN_AUTOMATIC(0)                                                       */
/* BINDTOOL_USE_PYGCCXML(0)                                                        */
/* BINDTOOL_HEADER_FILE(pulseaudio_sink.h)                                        */
/* BINDTOOL_HEADER_FILE_HASH(4cf9fda727518e2025fd1b5adbcec44c)                     */
/***********************************************************************************/

#include <pybind11/complex.h>
#include <pybind11/pybind11.h>
#include <pybind11/stl.h>

namespace py = pybind11;

#include <hnch/pulseaudio_sink.h>
// pydoc.h is automatically generated in the build directory
#include <pulseaudio_sink_pydoc.h>

void bind_pulseaudio_sink(py::module& m)
{

    using pulseaudio_sink    = ::gr::hnch::pulseaudio_sink;


    py::class_<pulseaudio_sink, gr::sync_block, gr::block, gr::basic_block,
        std::shared_ptr<pulseaudio_sink>>(m, "pulseaudio_sink", D(pulseaudio_sink))

        .def(py::init(&pulseaudio_sink::make),
           py::arg("samplingrate"),
           py::arg("sinkname"),
           py::arg("inchans"),
           py::arg("latency_ms"),
           D(pulseaudio_sink,make)
        )
        



        ;




}








